set(enabled_modules
  ACVD
  AlgorithmsExt
  AppUtil
  Core
  ContourModel
  CppMicroServices
  DataTypesExt
  DICOMReader
  DicomUI
  GraphAlgorithms
  ImageDenoising
  ImageExtraction
  ImageStatistics
  IOExt
  LegacyAdaptors
  LegacyGL
  LegacyIO
  MapperExt
  Multilabel
  Overlays
  PlanarFigure
  QmlItems
  QtWidgets
  QtWidgetsExt
  Remeshing
  RigidRegistration
  RigidRegistrationUI
  SceneSerialization
  SceneSerializationBase
  Segmentation
  SegmentationUI
  SurfaceInterpolation
)

set(enabled_plugins
  "org.blueberry.core.commands"
  "org.blueberry.core.expressions"
  "org.blueberry.core.runtime"
  "org.blueberry.ui.qt"
  "org.blueberry.ui.qt.help"
  "org.mitk.core.ext"
  "org.mitk.core.services"
  "org.mitk.gui.common"
  "org.mitk.gui.qt.application"
  "org.mitk.gui.qt.basicimageprocessing"
  "org.mitk.gui.qt.common"
  "org.mitk.gui.qt.common.legacy"
  "org.mitk.gui.qt.datamanager"
  "org.mitk.gui.qt.dicom"
  "org.mitk.gui.qt.extapplication"
  "org.mitk.gui.qt.ext"
  "org.mitk.gui.qt.imagecropper"
  "org.mitk.gui.qt.imagenavigator"
  "org.mitk.gui.qt.measurementtoolbox"
  "org.mitk.gui.qt.remeshing"
  "org.mitk.gui.qt.segmentation"
  "org.mitk.gui.qt.stdmultiwidgeteditor"
)
