set(Plugin-Name "UG Visualization")
set(Plugin-Version "0.1")
set(Plugin-Vendor "ZHAW")
set(Plugin-ContactAddress "https://simtk.org/home/mitk-gem")
set(Require-Plugin org.mitk.gui.qt.common.legacy ch.zhaw.gemapplication)
