set(Plugin-Name "UGrid Visualization")
set(Plugin-Version "1.0")
set(Plugin-Vendor "ZHAW")
set(Plugin-ContactAddress "https://simtk.org/home/mitk-gem")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.common.legacy ch.zhaw.gemapplication)
